// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using model;
using System;

namespace model.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("model.entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripción");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("model.entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("model.entities.UsuarioRol", b =>
                {
                    b.Property<int>("FKrol");

                    b.Property<int>("FKusuario");

                    b.HasKey("FKrol", "FKusuario");

                    b.HasIndex("FKusuario");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("model.entities.UsuarioRol", b =>
                {
                    b.HasOne("model.entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("FKrol")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("model.entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("FKusuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
